### ISSUE TITLE
Intronic read merge 

### ISSUE THREAD

**Issue by flde** [scfurl/mergeBams#1]
Hello mergeBams Team, 

Many thanks for the useful tool! With CellRanger v7 intronic reads are included and that might be useful for downstream genotyping. However, do you know if mergeBams includes intronic reads for merging or might there be a problem with the bam flags? 

So far, I have not noticed any issues but any input on the topic (e.g. how to validate that introns are merged) would be very much appreciated. 

All the best, 
Florian

**Comment by scfurl** [comment]
Hi Florian,

Thanks for using mergeBams.  Please note there is a much improved version of mergeBams here - https://github.com/furlan-lab/mergebams.  It is much faster and deals with the bam headers in a more responsible way.

Regarding your question, mergeBams doesn't detect for intronic/exonic reads before merging, so all reads will be merged regardless of whether or not they have introns.  All bam flags are copied and only the CB flag is changed by mergeBams.

Hope that answers your question!

S

**Comment by flde** [comment]
Hi @scfurl, 

Many thanks for the info and link to the updated version - I will check it out. Thats great news and thanks for maintaining mergeBams! 

Best wishes, 
Florian
